### ISSUE TITLE
testing through ratelimit

### ISSUE THREAD

**Issue by thockin** [juju/ratelimit#17]
We use ratelimit in Kubernetes.  I am working on something that uses it, and I am trying to write a test that doesn't actually take a long time to run.  As part of that I inject a fake clock interface.  It works really well until it hits the ratelimiter logic.

ratelimit uses `time.Now()` and `time.Sleep()` internally.  Would you be opposed to something like `NewBucketWithClock(..., clock Clock)` where `Clock` was an interface that wrapped `time.Now()` and similar functions?  Users who don't care will ignore it and get the default (which just calls the real `time.Now()`) and users who do care could provide a mocked clock.  If that is OK, I can try to work up a quick patch.

Or is there a better way to test through this?  I really don't want my test doing a bunch of 100ms sleeps to try to prove that it behaves.  I will have a number of cases to test and that adds up fast.

**Comment by howbazaar** [comment]
That is a very good idea, and one we should do quick smart. We have started using a Clock interface withing Juju itself, but this code was written before we started doing that I think.

**Comment by thockin** [comment]
Do our have a standard interface you want to use, or should I just send a
patch to use an internally defined interface for now?
