### ISSUE TITLE
Optimize NewBucketWithRateAndClock() method

### ISSUE THREAD

**Issue by helinbo2015** [juju/ratelimit#19]
In a for loop,  now it generates a `Bucket` object in each cycle, and only returns when the rate difference under 1%.  if called by a high rate, a huge of dummy `Bucket` objects are created.   

i think, it's more friendly that generates `Bucket` object only when rate difference under 1%.  and the code like:  
```
	for quantum := int64(1); quantum < 1<<50; quantum = nextQuantum(quantum) {
		fillInterval := time.Duration(1e9 * float64(quantum) / rate)
		if fillInterval <= 0 {
			continue
		}
		// tb := NewBucketWithQuantumAndClock(fillInterval, capacity, quantum, clock)
		if diff := math.Abs(1e9 * float64(quantum)/float64(fillInterval) - rate); diff/rate <= rateMargin {
			return NewBucketWithQuantumAndClock(fillInterval, capacity, quantum, clock)
		}
	}
```

@rogpeppe  if you accept this optiomization, i can  make a code MR. and any suggestion is welcome.

**Comment by rogpeppe** [comment]
Fixed by #20
