### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by fd0** [juju/ratelimit#24]
It'd be very helpful if you could tag a release. Thanks!

https://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases

**Comment by rogpeppe** [comment]
Thanks for prompting. Done. Tagged version 1.0.1 (because I got the 1.0.0 tag wrong initially!).

**Comment by fd0** [comment]
Cool, thanks!

**Comment by fd0** [comment]
I'm sorry to bother you again, but can you please add another tag called `v1.0.1` which points to the same commit as `1.0.1`? The new Go module support requires the `v` prefix for tags. Thank you very much!

**Comment by fd0** [comment]
Awesome, thanks!
